### ISSUE TITLE
Show some recently-created clubs on the `Clubs` page if there is no search query

### ISSUE THREAD

**Issue by bfbachmann** [ubclaunchpad/bounce#119]
Currently, when a user signs in they are met with a blank page. It would be good to show some recently created clubs to them if they haven't searched for anything. You'll need to fetch clubs from the back-end using `GET /clubs/search` with an empty query (see `ClubsSearchEndpoint` on the back-end).

**Comment by tariqa96** [comment]
- localhost:3000/create-club to display create club page.
