### ISSUE TITLE
Create simple DB schema for a Club

### ISSUE THREAD

**Issue by bfbachmann** [ubclaunchpad/bounce#2]
For reference https://files.slack.com/files-pri/T061Q8S7J-FAXSPQK3R/screen_shot_2018-05-26_at_12.27.51_pm.png

**Comment by ilovefroyos** [comment]
Create the relational database schema and the corresponding SQL for creating the tables in that schema.

**Comment by ilovefroyos** [comment]
[Bounce Web App Database - Version 1 Draft 1](https://drive.google.com/file/d/1qdNiRzLuWKVJmlQHr6cOmHimdm1tEBLZ/view)
