### ISSUE TITLE
Fix access to /clubs endpoint

### ISSUE THREAD

**Issue by bfbachmann** [ubclaunchpad/bounce#56]
Currently anyone with access to the API can CRUD clubs, but only people who own a club should be able to do that. This fix should involve making a user an owner of a club when creating a club and making sure that the owner is authenticated before serving delete or update requests on a club.

**Comment by ginsstaahh** [comment]
Currently we have as roles Admin, President, and Member, but not Owner...should it be only those who are Presidents can CRUD clubs?  I'm also assuming anyone can create or get clubs.  Its just presidents could only edit and delete.

**Comment by bfbachmann** [comment]
@ginsstaahh Yup, that makes sense to me!
