### ISSUE TITLE
Check for SQL injection vulnerabilities

### ISSUE THREAD

**Issue by bfbachmann** [ubclaunchpad/bounce#97]

**Comment by bfbachmann** [comment]
Check out https://www.metasploit.com/, it might be useful here.

**Comment by kevinyok** [comment]
@bfbachmann  I am opting to use either w3af or OWASP. Let me know if you have any feedback on the choice of tools. Metasploit does not seem to have modules well adapted to investigating vulnerabilities of web applications.

**Comment by bfbachmann** [comment]
One thing we should do is replace all statements like this https://github.com/ubclaunchpad/bounce/blob/master/bounce/db/membership.py#L64
to prepared statements like this:

```python
query = """SELECT users.id AS user_id,
    memberships.created_at, users.full_name, users.username FROM
    memberships INNER JOIN users ON (memberships.user_id = users.id)
    WHERE memberships.club_id IN (
    SELECT id FROM clubs WHERE name = :name
    )"""
session.execute(query, {'name': the_name})
```

Notice that instead of inserting the name directly into the query string I use a prepared statement with the key `name`. I then pass the name to `execute` as part of a dictionary so SQLAlchemy can escape any malicious SQL that might be in the name.
